apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ui
spec:
  selector:
    matchLabels:
      app: nginx-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui
        image: nginx:1.14.2
        ports:
        - containerPort: 80
